---
- name: "Creates backend app directory"
  become: true
  become_method: sudo
  shell: |
    mkdir /var/www
    sudo chown -R ubuntu:ubuntu /var/www
    sudo chmod 2775 /var/www

- name: "move backend gz"
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz
    backup: yes

- name: un-archived backend folder
  shell: |
    cd /home/ubuntu/
    tar -xvzf artifact.tar.gz

- name: execute backend
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start