---
- name: "Creates backend app directory"
  become: true
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend files"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Installing Node Dependencies"
  become: true
  shell: |
    # cd ~/backend-app 
    # curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    # sudo apt-get install -y nodejs
    # Install Node.js LTS version as our base Node.js version
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt update && apt install sudo curl && curl -sL https://raw.githubusercontent.com/Unitech/pm2/master/packager/setup.deb.sh | sudo -E bash -

    # sudo apt-get install -y nodejs

    # Use n version manager to use Node.js v13.8.0
    sudo npm install -g n
    sudo n 13.8.0
  
- name: "Install Node.js 13"
  become : true
  shell: |
     cd ~/backend-app
     npm install

- name: "Install PM2 Globally"
  become: true
  npm:
    name: pm2
    global: yes

- name: "Executing Node app with PM2"
  become : true
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print message
  become: true
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save